server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    registryFetchIntervalSeconds: 5  # Refresh service registry every 5s
  instance:
    preferIpAddress: true  # ✅ Use IP instead of hostname
    # hostname: localhost  # ✅ Ensures local resolution


spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
             - name: CircuitBreaker
               args:
                 name: userService
                 fallbackUri: forward:/fallback
        
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderService
                fallbackUri: forward:/fallback
          
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/inventory/**
          filters:
            - name: CircuitBreaker
              args:
                name: inventoryService
                fallbackUri: forward:/fallback

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 5s
    instances:
      userService:
        baseConfig: default
        slowCallDurationThreshold: 5s  # Overridden for orderService
      orderService:
        baseConfig: default
        slowCallDurationThreshold: 5s  # Overridden for orderService
      inventoryService:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 7s
    instances:
      userService:
        baseConfig: default
        timeoutDuration: 7s  # Overrides default 5s
      orderService:
        baseConfig: default
        timeoutDuration: 7s  # Overrides default 5s
      inventoryService:
        baseConfig: default

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.web: DEBUG

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
