server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true  # ✅ Use IP instead of hostname
    # hostname: localhost  # ✅ Ensures local resolution

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          # filters:
          #    - name: CircuitBreaker
          #      args:
          #        name: userServiceCircuitBreaker
          #        fallbackUri: forward:/fallback
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          # filters:
          #   - CircuitBreaker=customCircuitBreaker,forward:/fallback
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/inventory/**
          # filters:
          #   - CircuitBreaker=customCircuitBreaker,forward:/fallback

# resilience4j:
#   circuitbreaker:
#     instances:
#       customCircuitBreaker:
#         registerHealthIndicator: true
#         slidingWindowSize: 10
#         minimumNumberOfCalls: 5
#         permittedNumberOfCallsInHalfOpenState: 3
#         automaticTransitionFromOpenToHalfOpenEnabled: true
#         waitDurationInOpenState: 5000
#         failureRateThreshold: 50
#         slowCallRateThreshold: 100
#         slowCallDurationThreshold: 2000

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.web: DEBUG
