# server:
#   port: 8082

server:
  port: 0

spring:
  application:
    name: order-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    registryFetchIntervalSeconds: 5  # Refresh service registry every 5s
  instance:
    preferIpAddress: true  # ✅ Use IP instead of hostname
    # hostname: localhost  # ✅ Ensures local resolution

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/spring_cloud_microservices_poc

