# server:
#   port: 8081

server:
  port: 0

spring:
  application:
    name: User-Service

app:
  message: "Hello from local Profile!"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    registryFetchIntervalSeconds: 5  # Refresh service registry every 5s
  instance:
    # instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${server.port}
    preferIpAddress: true  # ✅ Use IP instead of hostname
    # hostname: localhost  # ✅ Ensures local resolution

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
  instances:
    orderCircuitBreaker:
      baseConfig: default
      waitDurationInOpenState: 5000

feign:
  client:
    config:
      default:
        connectTimeout: 2000   # 2 seconds
        readTimeout: 5000      # 5 seconds

