server:
  port: 8081

spring:
  application:
    name: User-Service

app:
  message: "Hello from Dev Profile! New"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true  # ✅ Use IP instead of hostname
    hostname: localhost  # ✅ Ensures local resolution
