# server:
#   port: 8081

server:
  port: 0

spring:
  application:
    name: User-Service

app:
  message: "Hello from local Profile!"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    # instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${server.port}
    preferIpAddress: true  # ✅ Use IP instead of hostname
    # hostname: localhost  # ✅ Ensures local resolution

resilience4j:
  circuitbreaker:
    instances:
      orderCircuitBreaker:
        registerHealthIndicator: true  # Expose circuit breaker health via the actuator
        slidingWindowSize: 10          # Size of the sliding window for call recording
        slidingWindowType: COUNT_BASED # Use count-based sliding window
        minimumNumberOfCalls: 10       # Minimum number of calls before calculating failure rate
        failureRateThreshold: 50       # If 50% (5 out of 10) calls fail, the circuit goes to OPEN state
        waitDurationInOpenState: 1s   # Time the circuit stays OPEN before moving to HALF_OPEN
        permittedNumberOfCallsInHalfOpenState: 3  # Number of test calls in HALF_OPEN state
        eventConsumerBufferSize: 10    # Buffer size for event logs

feign:
  client:
    config:
      default:
        errorDecoder: com.example.userservice.GlobalFeignErrorDecoder # Replace with your class path
